services:

  rg2-gazebo:
    image: husarion/ur-onrobot-rg2:noetic
    container_name: rg2-gazebo
    network_mode: host
    ipc: host
    tty: true
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      roslaunch onrobot_rg2_gazebo rg2_gazebo.launch

  rg2-rviz:
    image: husarion/ur-onrobot-rg2:noetic
    container_name: rg2-rviz
    network_mode: host
    ipc: host
    tty: true
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      roslaunch onrobot_rg2_description view_rg2.launch
        publish_robot_state:=False